<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="../assets/img/fav_icon/aperture.png"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/3707069c6e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../assets/css/normalize.css">
    <link rel="stylesheet" href="../assets/css/style.css">
    <title>Cyes Photographie BACK_OFFICE</title>
</head>
<body class="generalities">
    <header class="header">
     <nav class="container">
     <button  class="button button--neutral changeTheme">Dark Mode</button>
     <a class="button button--disconect" href="index.php?route=logout">
    <?php if(isset($_SESSION["connected"])): ?>
        <button class="button button--neutral button--disconect">Déconnexion</button>
    <?php endif ?>
    </a>
        <?php require_once "App/views/_nav.phtml" ?>
     </nav>
    </header>
    <main>
       <?php require_once $view . ".phtml" ?>
    </main>
    <footer>
    </footer>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="../assets/js/nav_translation.js" type="text/javascript"></script>
<script src="../assets/js/darkmode.js" type="text/javascript"></script>
<script src="../assets/js/masonry.js" type="text/javascript"></script>
<script src="../assets/js/masonry_script.js" type="text/javascript"></script>
</html>