<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/3707069c6e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../assets/css/normalize.css">
    <link rel="stylesheet" href="../assets/css/style.css">
    <title>Cyes Photographie BACK_OFFICE</title>
</head>
<body>
    <header class="header">
     <h1><a href="index.php?route=home">CYES PHOTOGRAPHIE</a></h1>
     <h2>BACK_OFFICE</h2>
     <nav>
        <?php require_once "App/views/_nav.phtml" ?>
     </nav>
    </header>

    <main>
       <?php require_once $view . ".phtml" ?>
    </main>

    <footer>
        <div>
            <h2></h2>
        </div>
    </footer>
    
</body>
</html>