<?php if(isset($_SESSION["connected"])): ?>
<ul>
    <li>
        <a href="index.php?route=album">Album Management</a>
    </li>
    <li>
        <a href="index.php?route=actualities">Actualities Management</a>
    </li>
    <li>
        <a href="index.php?route=about">About Management</a>
    </li>
    <li>
        <a href="index.php?route=messagerie">Messagerie</a>
    </li>
    <li>
        <a href="index.php?route=logout"><button>Se déconnecter</button></a>
    </li>
</ul>
<?php endif ?>