<div class="nav">
    <h1 class ="nav__title nav__title--homeAdmin">
        <a class="nav__title__link" href="index.php?route=home">CYES PHOTOGRAPHIE</a>
    </h1>
    <h2 class="nav__subTitle">BACK OFFICE</h2>
    <?php if(isset($_SESSION["connected"])): ?>
    <ul class="nav__menu">
        <li class="nav__menu__element">
            <a class="nav__menu__element__link" href="index.php?route=albums">Albums Management</a>
        </li>
        <li class="nav__menu__element">
            <a class="nav__menu__element__link" href="index.php?route=about">About Management</a>
        </li>
        <li class="nav__menu__element">
            <a class="nav__menu__element__link" href="index.php?route=actualities">Actualities Management</a>
        </li>
        <li class="nav__menu__element">
            <a class="nav__menu__element__link" href="index.php?route=mails">Messagerie</a>
        </li>
        <li class="nav__menu__element">
            <a class="nav__menu__element__link" href="index.php?route=admin">Mes infos administrateur</a>
        </li>
    </ul>
    <?php endif ?>
</div>

<div class="adminLogin">
    <?php if(!isset($_SESSION["connected"])): ?>
    <form class="adminLogin__form"action="index.php?route=login" method="POST">
        <label class="adminLogin__Label" for="login">Identifiant</label>
        <input class="adminLogin__input" id="login"type="text" name="login" autocomplete="off">
        <label class="adminLogin__Label" for="password">Mot de Passe</label>
        <input class="adminLogin__input" id="password"type="password" name="password" autocomplete="off">
        <button class="adminLogin__ValidateButton">Valider</button>
    </form>
    <?php endif ?>
</div>