<div class="nav">
    <h1 class ="nav__title-admin nav__title-admin--home">
        <a class="link__style link__nav-hover" href="home">CYES PHOTOGRAPHIE</a>
    </h1>
    <h2 class="nav__admin-subtitle">BACK OFFICE</h2>
    <?php if(isset($_SESSION["connected"])): ?>
    <ul class="nav__list nav__list--homeAdmin">
        <li class="nav__element">
            <a class="link__style link__nav-hover" href="albums">Albums Management</a>
        </li>
        <li class="nav__element">
            <a class="link__style link__nav-hover" href="about">About Management</a>
        </li>
        <li class="nav__element">
            <a class="link__style link__nav-hover" href="actualities">Actualities Management</a>
        </li>
        <li class="nav__element">
            <a class="link__style link__nav-hover" href="mails">Messagerie</a>
        </li>
        <li class="nav__element">
            <a class="link__style link__nav-hover" href="admin">Mes infos administrateur</a>
        </li>
    </ul>
    <?php endif ?>
</div>

<div>
    <?php if(!isset($_SESSION["connected"])): ?>
    <form class="form__card form__card--admin-connect" action="index.php?route=login" method="POST">
        <div class="form__fields">
            <label class="form__label" for="login">Identifiant</label>
            <input class="form__input" id="login" type="text" name="login" autocomplete="off">
        </div>
        <div class="form__fields">
            <label class="form__label" for="password">Mot de Passe</label>
            <input class="form__input" id="password" type="password" name="password" autocomplete="off">
        </div>
        <div class="button__group">
            <button class="button button--neutral">Valider</button>
        </div>
    </form>
    <?php endif ?>
</div>