<section>
    <?php foreach($contents as $content): ?>
    <article>
        <img src="../assets/img/actu_img/<?=$content["act_photo"] ?>" alt="photo d'illustration de l'article">
        <h2><?=$content["act_title"]?></h2>
        <p><?=$content["act_date"]?></p>
        <p><?=$content["act_content"]?></p>
        <a href="index.php?route=deleteActualitie&act_id=<?= htmlspecialchars($content["act_id"]) ?>">
            <button>Supprimer</button>
        </a>
    </article>
    <?php endforeach ?>
</section>