<section class="container">
    <h3 class="form__title">Ajouter une actualité :</h3>
    <form class="form__card"method = "POST" enctype="multipart/form-data" action="index.php?route=addActualitie">
        <div class="form__fields">
            <label class="form__label" for="act_photo">Photo de présentation : </label>
            <?php if(isset($errors) && array_key_exists("photo", $errors)):?>
                <?= htmlspecialchars($errors["photo"])?>
            <?php endif?>
            <input class="form__input" id = "act_photo" type="file" name = "act_photo">
        </div>
        <div class="form__fields">
            <label class="form__label" for="act_title">Nom de l'actualité :</label>
            <?php if(isset($errors) && array_key_exists("title", $errors)):?>
                <p class="form__error"><?= htmlspecialchars($errors["title"])?></p>
            <?php endif?>
            <input class="form__input" id = "act_title" type="text" name = "act_title">
        </div>
        <div class="form__fields">
            <label class="form__label" for="act_date">Date :</label>
            <?php if(isset($errors) && array_key_exists("date", $errors)):?>
                <p class="form__error"><?= htmlspecialchars($errors["date"])?></p>
            <?php endif?>
            <input class="form__input" id = "act_date" type="date" name = "act_date">
        </div>
        <div class="form__fields">
            <label class="actualities__form__label" for="act_content">Description :</label>
            <?php if(isset($errors) && array_key_exists("text", $errors)):?>
                <p class="form__error"><?= htmlspecialchars($errors["text"])?></p>
            <?php endif?>
            <textarea class="form__text-arrea"name="act_content" id="act_content"></textarea>
        </div>
            <button class="button button--validate">Valider</button>
    </form>
    <div class="previews__group-card">
        <?php foreach($contents as $content): ?>
            <article class="previews__card">
                <div class="underline-decoration"></div>
                <img class="previews__img" src="../assets/img/actu_img/<?=htmlspecialchars($content["act_photo"])?>" alt="photo d'illustration de l'article">
                <form class="form__card" method ="POST" enctype="multipart/form-data" action="index.php?route=updateActualitie&act_id=<?=htmlspecialchars($content["act_id"])?>">
                    <div class="form__fields">
                        <label class="form__label" for="act_photo">Modifier la photo :</label>
                        <?php if(isset($errors) && array_key_exists("updatePhoto", $errors)):?>
                            <p class="form__error"><?=htmlspecialchars($errors["updatePhoto"])?></p>
                        <?php endif?>
                        <input class="form__input" id="act_photo" type="file" name="act_photo">
                    </div>
                    <div class="form__fields">
                        <label class="form__label" for="act_title">Modifier le titre :</label>
                        <input class="form__input" id="act_title" type="text" name="act_title" value="<?=htmlspecialchars($content["act_title"])?>">
                    </div>
                    <div class="form__fields">
                        <label class="form__label" for="act_date">Modifier la date :</label>
                        <input class="form__input" id="act_date" type="date" name="act_date" value="<?=htmlspecialchars($content["act_date"])?>">
                    </div>
                    <div class="form__fields">
                        <label class="form__label" for="act_content">Modifier la description :</label>
                        <textarea class="form__text-arrea" id="act_content" type="text" name="act_content"><?=htmlspecialchars($content["act_content"])?></textarea>
                    </div>
                    <button class="button button--validate">Valider</button>
                </form>
                <a class="link__style" href="index.php?route=deleteActualitie&act_id=<?= htmlspecialchars($content["act_id"]) ?>">
                    <button class="button button--delete">Supprimer</button>
                </a>
            </article>
        <?php endforeach ?>
    </div>
</section>