<section class="Galleries">
    <?php foreach($albums as $album): ?>
        <select name="categories">
            <option value="#">Filtrez par catégorie</option>
            <option value="<?= htmlspecialchars($album["albm_cat_id"])?>">Mariages</option>
        </select>
        <article>
            <a href="index.php?route=gallery&id=<?=htmlspecialchars($album["albm_id"])?>"><img src="../assets/img/albm_photos/<?= htmlspecialchars($album["albm_photo"])?>" alt="Photo de présentation des catégories"></a>
            <h2><?=htmlspecialchars($album["albm_title"])?></h2>
            <a href="#">
                <button>Modifier</button>
            </a>
            <a href="index.php?route=deleteAlbum&albm_id=<?=htmlspecialchars($album["albm_id"])?>&albm_photo=<?=htmlspecialchars($album["albm_photo"])?>">
                <button>Supprimer</button>
            </a>
        </article>
    <?php endforeach ?>

    <h3>Ajouter un Album :</h3>
    <form action="index.php?route=addAlbum" method="POST">
        
        <label id="categories"></label>
        <select name="categories" id="categories">
            <!-- Sélecteur de catégorie -->
            <option value="">Catégorie</option>
            <?php foreach($categories as $categorie):?>
            <option value="<?= htmlspecialchars($categorie["cat_name"])?>"><?= htmlspecialchars($categorie["cat_name"])?></option>
            <?php endforeach ?>
        </select>

        <label id="title"></label>
        <input id="title" type="text" name="title" placeholder="Titre">

        <label id="description"></label>
        <input id="description" type="text" name="description" placeholder="Description">

        <label id="photoName"></label>
        <input id="photoName" type="file" name="photoName" placeholder="Photo de Présentation">

    <button>Valider</button>
    </form>
</section>