<section class="container">
<h3 class="form__title">Mes Messages :</h3>
    <div class="mails__group-card">
        <?php foreach($mails as $mail): ?>
            <a class="link__style mails__link" href="index.php?route=mail&id=<?=htmlspecialchars($mail["cont_id"])?>">
            <article class="mails__card">
                <p class="mails__date">
                    <?= htmlspecialchars($mail["cont_date"])?>
                </p>
                <div class="mails__identity-group">
                        <i class="fa-regular fa-user mails__link"></i>
                        <p class="mails__identity-content">
                        <?= htmlspecialchars($mail["cont_usr_lastname"])?>
                    </p>
                    <p class="mails__identity-content">
                        <?= htmlspecialchars($mail["cont_usr_firstname"])?>
                    </p>
                </div>
                <p class="mails__subject">
                    <?= htmlspecialchars($mail["cont_usr_subject"])?>
                </p>
                <p class="overflow">
                    <?=htmlspecialchars($mail["cont_usr_content"])?>
                </p>
            </article>
            </a>
        <?php endforeach ?>
    </div>
</section>