<section>
    <table>
        <?php foreach($mails as $mail): ?>
        <tr>
            <td>
            <a href="index.php?route=mail&id=<?=htmlspecialchars($mail["cont_id"])?>">
                <?= htmlspecialchars($mail["cont_date"])?>
                </a>
            </td>
            <td>
            <a href="index.php?route=mail&id=<?=htmlspecialchars($mail["cont_id"])?>">
                    <?= htmlspecialchars($mail["cont_usr_lastname"]) ?>
                </a>
            </td>
            <td>
            <a href="index.php?route=mail&id=<?=htmlspecialchars($mail["cont_id"])?>">
                    <?= htmlspecialchars($mail["cont_usr_firstname"])?>
                </a>
            </td>
            <td>
            <a href="index.php?route=mail&id=<?=htmlspecialchars($mail["cont_id"])?>">
                    <?= htmlspecialchars($mail["cont_usr_content"])  ?>
                </a>
            </td>
        </tr>
        <?php endforeach ?>
    </table>
</section>