<section class="container">
    <article class="mail__card">
        <p class="mail__date"> le <?= htmlspecialchars($mail["cont_date"])?></p>
        <div class="mail__identity">
            <p class="mail__usr-name"><?= htmlspecialchars($mail["cont_usr_firstname"])?></p>
            <p class="mail__usr-name"><?= htmlspecialchars($mail["cont_usr_lastname"])?></p>
        </div>
        <div class="mail__usr-info">
            <p><?= htmlspecialchars($mail["cont_usr_mail"])?></p>
            <p><?= htmlspecialchars($mail["cont_usr_tel"])?></p>
        </div>
        <p class="mail__text mail__subject"><?= htmlspecialchars($mail["cont_usr_subject"])?></p>
        <p class="mail__text"><?= htmlspecialchars($mail["cont_usr_content"])?></p>
        <a class="link__style" href="index.php?route=deleteMail&id=<?= htmlspecialchars($mail["cont_id"])?>">
            <button class="button button--delete">Supprimer</button>
        </a>
    </article>
</section>