<section>
    <h3><?=htmlspecialchars($album["albm_title"])?></h2>
    <p><?=htmlspecialchars($album["albm_description"])?></p>
    <?php foreach($photos as $photo): ?>
        <img src="../assets/img/photos/<?=htmlspecialchars($photo["pht_albm_id"])?>/<?=htmlspecialchars($photo["pht_name"]) ?>" alt="photo de la gallerie">
        <a href="">
            <button>Modifier</button>
        </a>
        <a href="index.php?route=deletePhoto&albm_id=<?= htmlspecialchars($album["albm_id"]) ?>&pht_name=<?= htmlspecialchars($photo["pht_name"]) ?>">
            <button>Supprimer</button>
        </a>
    <?php endforeach; ?>
    <form action="index.php?route=addPhotos" enctype="multipart/form-data" method="POST">
        <label id="photos"></label>
        <input type="file" multiple="true" name="photos">
        <input type="hidden" name="albm_id" value="<?=htmlspecialchars($album["albm_id"])?>">
        <button>Valider</button>
    </form>
</section>