<ul class="nav">
    <li class="nav__element">
        <h1 class ="nav__element_title">
            <a class="nav__element__link" href="index.php?route=home">CYES PHOTOGRAPHIE</a>
        </h1>
    </li>
    <li class="nav__element">
        <a class="nav__element__link" href="index.php?route=galleries">Galerie</a>
    </li>
    <li class="nav__element">
        <a class="nav__element__link" href="index.php?route=about">À propos</a>
    </li>
    <li class="nav__element">
        <a class="nav__element__link" href="index.php?route=actualities">Actualité</a>
    </li>
    <li class="nav__element">
        <a class="nav__element__link" href="index.php?route=contact">Contact</a>
    </li>
</ul>