<div class="nav">
    <h1 class="nav__title nav__title--home">
        <a class="link__style link__nav-hover" href="home">CYES PHOTOGRAPHIE</a>
    </h1>
    <ul class=nav__list>
        <li class="nav__element">
            <a class="link__style link__nav-hover" href="albums">Albums</a>
        </li>
        <li class="nav__element">
            <a class="link__style link__nav-hover" href="about">À propos</a>
        </li>
        <li class="nav__element">
            <a class="link__style link__nav-hover" href="actualities">Actualité</a>
        </li>
        <li class="nav__element">
            <a class="link__style link__nav-hover" href="contact">Contact</a>
        </li>
    </ul>
</div>