<div class="nav container">
        <h1 class ="nav__title nav__title--home">
            <a class="nav__title__link" href="index.php?route=home">CYES PHOTOGRAPHIE</a>
        </h1>
    <ul class="nav__menu">
        <li class="nav__menu__element">
            <a class="nav__menu__element__link" href="index.php?route=albums">Galerie</a>
        </li>
        <li class="nav__menu__element">
            <a class="nav__menu__element__link" href="index.php?route=about">À propos</a>
        </li>
        <li class="nav__menu__element">
            <a class="nav__menu__element__link" href="index.php?route=actualities">Actualité</a>
        </li>
        <li class="nav__menu__element">
            <a class="nav__menu__element__link" href="index.php?route=contact">Contact</a>
        </li>
    </ul>
</div>