<section class="container">
    <article class="about__card">
        <img class="image__large image__large--about" src="assets/img/about_img/<?=htmlspecialchars($about["abt_photo"])?>" alt="Portrait du photographe">
        <p class="text__article"><?= htmlspecialchars($about["abt_content"])?></p>
    </article>
    <div class="social-media__groups">
        <?php if(!empty($about["abt_facebook"])): ?>
        <a class="link__style" target="_blank" href="<?= htmlspecialchars($about["abt_facebook"])?>"><i class="fa-brands fa-facebook"></i></a>
        <?php endif ?>
        <?php if(!empty($about["abt_instagram"])): ?>
        <a class="link__style" target="_blank" href="<?= htmlspecialchars($about["abt_instagram"])?>"><i class="fa-brands fa-instagram"></i></a>
        <?php endif ?>
        <?php if(!empty($about["abt_twitter"])): ?>
        <a class="link__style" target="_blank" href="<?= htmlspecialchars($about["abt_twitter"])?>"><i class="fa-brands fa-twitter-square"></i></a>
        <?php endif ?>
    </div>
</section>