<section class="container">
    <div class="previews__group-card">
        <?php foreach($contents as $content): ?>
            <article class="previews__card">
                <img class="previews__img" src="assets/img/actu_img/<?=$content["act_photo"] ?>" alt="photo d'illustration de l'article">
                <h2 class="previews__title"><?=$content["act_title"]?></h2>
                <p class="previews__text"><?=$content["act_date"]?></p>
                <p class="previews__text"><?=$content["act_content"]?></p>
                <div class="underline-decoration"></div>
            </article>
        <?php endforeach ?>
    </div>
</section>