<section>
    <form action= "index.php?route=validation" method="POST">
        <div>
            <label for="lastname">Nom :</label>
            <?php if( isset($errors) && array_key_exists("e1",$errors) ): ?>
                <p><?= $errors["e1"] ?></p>
            <?php endif ?>
            <input id="lastname" type="text" name="lastname" value="<?= htmlspecialchars(@$_POST["lastname"]) ?>"> 
        </div>
        <div>
            <label for="firstname">Prénom :</label>
            <?php if( isset($errors) && array_key_exists("e2",$errors) ) : ?>
                <p class="form__error"><?= $errors["e2"] ?></p>
            <?php endif ?>
            <input id="firstname" type="text" name="firstname" value="<?= htmlspecialchars(@$_POST["firstname"]) ?>">
        </div>
        <div>
            <label for="tel">Téléphone :</label>
            <?php if( isset($errors) && array_key_exists("e3",$errors) ) : ?>
                <p class="form__error"><?= $errors["e3"] ?></p>
            <?php endif ?>
            <input id="tel" type="tel" name="tel" value="<?= htmlspecialchars(@$_POST["tel"]) ?>">
        </div>
        <div>
            <label for="mail">Email :</label>
            <?php if( isset($errors) && array_key_exists("e4",$errors) ) : ?>
                <p><?= $errors["e4"] ?></p>
            <?php endif ?>
            <input id="mail" type="mail" name="mail" value="<?= htmlspecialchars(@$_POST["mail"]) ?>">
        </div>
        <div>
            <label for="subject">Objet :</label>
            <?php if( isset($errors) && array_key_exists("e5",$errors) ) : ?>
                <p><?= $errors["e5"] ?></p>
            <?php endif ?>
            <input id="subject" name="subject" value="<?=htmlspecialchars(@$_POST["subject"]) ?>">
        </div>
        <div>
            <label for="content">Votre demande :</label>
            <?php if( isset($errors) && array_key_exists("e6",$errors) ) : ?>
                <p><?= $errors["e6"] ?></p>
            <?php endif ?>
            <textarea id="content" name="content"><?=htmlspecialchars(@$_POST["content"]) ?></textarea>
        </div>
        <button type="submit">Envoyer</button>
    </form>
</section>