<section class="container">
    <div class="underline-decoration"></div>
    <div class="albums__presentation">
        <h2 class="text__alb-title"><?= htmlspecialchars($album["albm_title"]) ?></h2>
        <p class="text__alb-content"><?= htmlspecialchars($album["albm_description"])?></p>
    </div>
    <div class="underline-decoration"></div>
    <div class="grid">
        <?php foreach ($photos as $photo) : ?>
            <div class="grid-item">
                <a loading="lazy" href="assets/img/photos/<?= htmlspecialchars($photo["pht_albm_id"]) ?>/<?= htmlspecialchars($photo["pht_name"]) ?>"
                data-fancybox="gallery">
                <img loading="lazy" class="image__large" src="assets/img/thumbnails/<?= htmlspecialchars($photo["pht_albm_id"]) ?>/<?= htmlspecialchars($photo["pht_name"]) ?>" alt="photo de la gallerie">
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</section>