<section class="container">
    <div class="underline-decoration"></div>
    <div class="albums__presentation">
    <h2 class="text__alb-title"><?= htmlspecialchars($album["albm_title"]) ?></h2>
    <p class="text__alb-content"><?= htmlspecialchars($album["albm_description"]) ?></p>
    </div>
    <div class="underline-decoration"></div>
    <?php foreach ($photos as $photo) : ?>
        <img class="image__large" src="assets/img/photos/<?= htmlspecialchars($photo["pht_albm_id"]) ?>/<?= htmlspecialchars($photo["pht_name"]) ?>" alt="photo de la gallerie">
    <?php endforeach; ?>
</section>