<section class="Galleries">
    <?php foreach($albums as $album): ?>
        <select name="categories">
            <option value="#">Filtrez par catégorie</option>
            <option value="<?= htmlspecialchars($album["albm_cat_id"])?>">Mariages</option>
        </select>
        <article>
            <a href="index.php?route=photos&id=<?=htmlspecialchars($album["albm_id"])?>"><img src="assets/img/albm_photos/<?= htmlspecialchars($album["albm_photo"])?>" alt="Photo de présentation des catégories"></a>
            <h2><?=htmlspecialchars($album["albm_title"])?></h2>
        </article>
    <?php endforeach ?>
</section>