<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/css/normalize.css">
    <link rel="stylesheet" href="assets/css/style.css">
    <title>Bidule Photographie</title>
</head>
<body>
    <header class="header">
     <h1>CYES PHOTOGRAPHIE</h1>
     <nav>
        <?php require_once "App/views/nav.phtml" ?>
     </nav>
    </header>

    <main>
       <?php require_once $view . ".phtml" ?>
    </main>

    <footer>
        <div>
            <h2>Footer du layout</h2>
        </div>
    </footer>
    
</body>
</html>