<section>
    <form action= "index.php?route=validation" method="POST">

        <label for="test1"></label>
        <input type="text" name="test1" placeholder="test1">

        <label for="test2"></label>
        <input type="text" name="test2" placeholder="test2">

        <button type="submit">Valider</button>
    </form>
    <?php if( isset($_GET['errorMessage']) ) : ?>
        <?= htmlspecialchars($_GET['errorMessage'])  ?>
    <?php endif ?>
</section>