<section>
    <form action= "index.php?route=validation" method="POST">
        <div>
            <label for="test1"></label>
            <input type="text" name="test1" placeholder="test1">
            <?php if( isset($errors) && array_key_exists(0,$errors) ): ?>
                <p><?= $errors[0] ?></p>
            <?php endif ?>
        </div>
        <div>
            <label for="test2"></label>
            <input type="text" name="test2" placeholder="test2">
            <?php if( isset($errors) && array_key_exists(1,$errors) ) : ?>
                <p><?= $errors[1] ?></p>
            <?php endif ?>
        </div>
        <button type="submit">Valider</button>
        <?php if(isset($valid) && !empty($valid)): ?>
            <p><?= $valid ?></p>
        <?php endif ?>
    </form>
</section>