<h2>Test Connection Base de Donnée</h2>

<div>
    <?php
        $servername = 'localhost';
        $username = 'root';
        $password = '';
        //On établit la connexion
        $conn = new mysqli($servername, $username, $password);
        //On vérifie la connexion
        if($conn->connect_error){
                die('Erreur : ' .$conn->connect_error);
                }
        echo 'Connexion réussie';
        ?>
</div>